version: "3.8"
services:
  server:
    build: ./nodescripts
    container_name: puppeteer-server
    ports:
      - "4000:4000"

  frontend:
    build: ./productsmvp
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
