version: "3.8"

services:
  nodescripts:
    build: .
    container_name: nodescripts
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    # Optional: mount your working dir for local development
    # volumes:
    #   - .:/app
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/v1/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
