const DEFAULT_STORES = [
  { name: 'Kith', url: 'https://kith.com', active: false },
  { name: 'Allbirds', url: 'https://www.allbirds.com', active: false },
  { name: 'Brooklinen', url: 'https://www.brooklinen.com', active: false },
  { name: 'Rothy\'s', url: 'https://rothys.com', active: false },
  { name: 'Taylor Stitch', url: 'https://www.taylorstitch.com', active: false },
  { name: 'Chubbies', url: 'https://chubbies.com', active: false },
  { name: 'Untuckit', url: 'https://untuckit.com', active: false },
  { name: 'Mack Weldon', url: 'https://mackweldon.com', active: false },
  { name: 'ThirdLove', url: 'https://www.thirdlove.com', active: false },
  { name: 'Cuyana', url: 'https://cuyana.com', active: false },
  { name: 'Hill House Home', url: 'https://hillhousehome.com', active: false },
  { name: 'Parachute Home', url: 'https://parachutehome.com', active: false },
  { name: 'Outerknown', url: 'https://www.outerknown.com', active: false },
  { name: 'Everlane', url: 'https://www.everlane.com', active: false },
  { name: 'Casper', url: 'https://casper.com', active: false },
  { name: 'Tuft & Needle', url: 'https://www.tuftandneedle.com', active: false },
  { name: 'Floyd Home', url: 'https://floydhome.com', active: false },
  { name: 'The Citizenry', url: 'https://the-citizenry.com', active: false },
  { name: 'Our Place', url: 'https://fromourplace.com', active: false },
  { name: 'Greats', url: 'https://greats.com', active: false },
  { name: 'Oliver Cabell', url: 'https://www.olivercabell.com', active: false },
  { name: 'Cariuma', url: 'https://cariuma.com', active: false },
  { name: 'Birdies', url: 'https://birdies.com', active: false },
  { name: 'Champion', url: 'https://www.champion.com', active: false },
  { name: 'Aime Leon Dore', url: 'https://www.aimeleondore.com', active: false },
  { name: 'Noah', url: 'https://www.noahny.com', active: false },
  { name: 'Fear of God', url: 'https://fearofgod.com', active: false },
  { name: 'Amiri', url: 'https://amiri.com', active: false },
  { name: 'John Elliott', url: 'https://johnelliott.com', active: false },
  { name: 'A Cold Wall', url: 'https://acoldwall.com', active: false },
  { name: 'Martine Rose', url: 'https://martine-rose.com', active: false },
  { name: 'Grace Wales Bonner', url: 'https://walesbonner.net', active: false },
  { name: 'Simone Rocha', url: 'https://simonerocha.com', active: false },
  { name: 'Molly Goddard', url: 'https://mollygoddard.com', active: false },
  { name: 'Sophie Bille Brahe', url: 'https://sophiebillebrahe.com', active: false },
  { name: 'Completedworks', url: 'https://completedworks.com', active: false },
  { name: 'Edge of Ember', url: 'https://edgeofember.com', active: false },
  { name: 'Missoma', url: 'https://missoma.com', active: false },
  { name: 'Oscar de la Renta', url: 'https://www.oscardelarenta.com', active: false },
  { name: 'Zac Posen', url: 'https://zacposen.com', active: false },
  { name: 'Jason Wu', url: 'https://jasonwustudio.com', active: false },
  { name: 'Prabal Gurung', url: 'https://prabalgurung.com', active: false },
  { name: 'Joseph Altuzarra', url: 'https://altuzarra.com', active: false },
  { name: 'Monse', url: 'https://monse.com', active: false },
  { name: 'Collina Strada', url: 'https://collinastrada.com', active: false },
  { name: 'Batsheva', url: 'https://batsheva.com', active: false },
  { name: 'Staud', url: 'https://staud.clothing', active: false },
  { name: 'Cecilie Bahnsen', url: 'https://ceciliebahnsen.com', active: false },
  { name: 'House of Sunny', url: 'https://houseofsunny.co.uk', active: false },
  { name: 'With Jéan', url: 'https://withjean.com', active: false },
  { name: 'Rat & Boa', url: 'https://ratandboa.com', active: false },
  { name: 'Faithfull the Brand', url: 'https://faithfullthebrand.com', active: false },
  { name: 'Christopher Esber', url: 'https://christopheresber.com', active: false },
  { name: 'Manning Cartell', url: 'https://manningcartell.com', active: false },
  { name: 'Bec & Bridge', url: 'https://becandbridge.com', active: false },
  { name: 'Aje Athletica', url: 'https://ajeathletica.com', active: false },
  { name: 'Beyond Yoga', url: 'https://beyondyoga.com', active: false },
  { name: 'Tully Lou', url: 'https://tullylou.com', active: false },
  { name: 'Year of Ours', url: 'https://yearofours.com', active: false },
  { name: 'Ten Thousand', url: 'https://tenthousand.cc', active: false },
  { name: 'Bearbottom Clothing', url: 'https://bearbottomclothing.com', active: false },
  { name: 'Southern Tide', url: 'https://southerntide.com', active: false },
  { name: 'Southern Marsh', url: 'https://southernmarsh.com', active: false },
  { name: 'The Black Tux', url: 'https://theblacktux.com', active: false },
  { name: 'Rent the Runway', url: 'https://www.renttherunway.com', active: false },
  { name: 'A.L.C.', url: 'https://alcltd.com', active: false },
  { name: 'AG Jeans', url: 'https://agjeans.com', active: false },
  { name: 'Joe\'s Jeans', url: 'https://joesjeans.com', active: false },
  { name: 'Hudson Jeans', url: 'https://hudsonjeans.com', active: false },
  { name: 'Mother Denim', url: 'https://motherdenim.com', active: false },
  { name: 'DL1961', url: 'https://dl1961.com', active: false },
  { name: 'Good American', url: 'https://goodamerican.com', active: false },
  { name: 'Re/Done', url: 'https://shopredone.com', active: false },
  { name: 'A Gold E', url: 'https://agolde.com', active: false },
  { name: 'Hey Dude', url: 'https://heydude.com', active: false },
  { name: 'Koio', url: 'https://koio.co', active: false },
  { name: 'Thursday Boots', url: 'https://thursdayboots.com', active: false },
  { name: 'Blundstone', url: 'https://blundstone.com', active: false },
  { name: 'Keen', url: 'https://keenfootwear.com', active: false },
  { name: 'Sanuk', url: 'https://sanuk.com', active: false },
  { name: 'Olukai', url: 'https://olukai.com', active: false },
  { name: 'Margaux', url: 'https://margauxny.com', active: false },
  { name: 'Sarah Flint', url: 'https://sarahflint.com', active: false },
  { name: 'M.Gemi', url: 'https://mgemi.com', active: false },
  { name: 'Beckett Simonon', url: 'https://beckettsimonon.com', active: false },
  { name: 'Meermin', url: 'https://meermin.com', active: false },
  { name: 'Rancourt & Co.', url: 'https://rancourtandcompany.com', active: false },
  { name: 'Russell Moccasin', url: 'https://russellmoccasin.com', active: false },
  { name: 'Filson', url: 'https://filson.com', active: false },
  { name: 'Outdoor Research', url: 'https://outdoorresearch.com', active: false },
  { name: 'Black Diamond', url: 'https://blackdiamondequipment.com', active: false },
  { name: 'Campmor', url: 'https://campmor.com', active: false },
  { name: 'Eastern Mountain Sports', url: 'https://ems.com', active: false },
  { name: 'Sunski', url: 'https://sunski.com', active: false },
  { name: 'Shady Rays', url: 'https://shadyrays.com', active: false },
  { name: 'Blenders Eyewear', url: 'https://blenderseyewear.com', active: false },
  { name: 'Knockaround', url: 'https://knockaround.com', active: false },
  { name: 'Felix Gray', url: 'https://felixgray.com', active: false },
  { name: 'Peepers', url: 'https://peepers.com', active: false },
  { name: 'Electric', url: 'https://electriccalifornia.com', active: false },
  { name: 'VonZipper', url: 'https://vonzipper.com', active: false },
  { name: 'Polaroid Eyewear', url: 'https://polaroideyewear.com', active: false },
  { name: 'Revo', url: 'https://revo.com', active: false },
  { name: 'Issey Miyake', url: 'https://isseymiyake.com', active: false },
  { name: 'Bape', url: 'https://bape.com', active: false },
  { name: 'Neighborhood', url: 'https://neighborhood.jp', active: false },
  { name: 'MATE the Label', url: 'https://matethelabel.com', active: false },
  { name: 'Coperni', url: 'https://coperni.com', active: false },
  { name: 'Dylan Lex', url: 'https://dylanlex.com', active: false },
  { name: 'Wray', url: 'https://wray.nyc', active: false },
  { name: 'Bode', url: 'https://bode.com', active: false },
  { name: 'Batsheva', url: 'https://batsheva.com', active: false },
  { name: 'Staud', url: 'https://staud.clothing', active: false },
  { name: 'Cecilie Bahnsen', url: 'https://ceciliebahnsen.com', active: false },
  { name: 'House of Sunny', url: 'https://houseofsunny.co.uk', active: false },
  { name: 'With Jéan', url: 'https://withjean.com', active: false },
  { name: 'Rat & Boa', url: 'https://ratandboa.com', active: false },
  { name: 'Faithfull the Brand', url: 'https://faithfullthebrand.com', active: false },
  { name: 'Christopher Esber', url: 'https://christopheresber.com', active: false },
  { name: 'Manning Cartell', url: 'https://manningcartell.com', active: false },
  { name: 'Bec & Bridge', url: 'https://becandbridge.com', active: false },
  { name: 'Aje Athletica', url: 'https://ajeathletica.com', active: false },
  { name: 'Beyond Yoga', url: 'https://beyondyoga.com', active: false },
  { name: 'Tully Lou', url: 'https://tullylou.com', active: false },
  { name: 'Year of Ours', url: 'https://yearofours.com', active: false },
  { name: 'Ten Thousand', url: 'https://tenthousand.cc', active: false },
  { name: 'Bearbottom Clothing', url: 'https://bearbottomclothing.com', active: false },
  { name: 'Southern Tide', url: 'https://southerntide.com', active: false },
  { name: 'Southern Marsh', url: 'https://southernmarsh.com', active: false },
  { name: 'The Black Tux', url: 'https://theblacktux.com', active: false },
  { name: 'Rent the Runway', url: 'https://www.renttherunway.com', active: false },
  { name: 'A.L.C.', url: 'https://alcltd.com', active: false },
  { name: 'AG Jeans', url: 'https://agjeans.com', active: false },
  { name: 'Joe\'s Jeans', url: 'https://joesjeans.com', active: false },
  { name: 'Hudson Jeans', url: 'https://hudsonjeans.com', active: false },
  { name: 'Mother Denim', url: 'https://motherdenim.com', active: false },
  { name: 'DL1961', url: 'https://dl1961.com', active: false },
  { name: 'Good American', url: 'https://goodamerican.com', active: false },
  { name: 'Re/Done', url: 'https://shopredone.com', active: false },
  { name: 'A Gold E', url: 'https://agolde.com', active: false },
  { name: 'Hey Dude', url: 'https://heydude.com', active: false },
  { name: 'Koio', url: 'https://koio.co', active: false },
  { name: 'Thursday Boots', url: 'https://thursdayboots.com', active: false },
  { name: 'Blundstone', url: 'https://blundstone.com', active: false },
  { name: 'Keen', url: 'https://keenfootwear.com', active: false },
  { name: 'Sanuk', url: 'https://sanuk.com', active: false },
  { name: 'Olukai', url: 'https://olukai.com', active: false },
  { name: 'Margaux', url: 'https://margauxny.com', active: false },
  { name: 'Sarah Flint', url: 'https://sarahflint.com', active: false },
  { name: 'M.Gemi', url: 'https://mgemi.com', active: false },
  { name: 'Beckett Simonon', url: 'https://beckettsimonon.com', active: false },
  { name: 'Meermin', url: 'https://meermin.com', active: false },
  { name: 'Rancourt & Co.', url: 'https://rancourtandcompany.com', active: false },
  { name: 'Russell Moccasin', url: 'https://russellmoccasin.com', active: false },
  { name: 'Filson', url: 'https://filson.com', active: false },
  { name: 'Outdoor Research', url: 'https://outdoorresearch.com', active: false },
  { name: 'Black Diamond', url: 'https://blackdiamondequipment.com', active: false },
  { name: 'Campmor', url: 'https://campmor.com', active: false },
  { name: 'Eastern Mountain Sports', url: 'https://ems.com', active: false }
];